[build]
  publish = "."
  command = "echo 'No build needed for static site'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  # Configuração de headers para segurança e performance
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com;
      font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com;
      img-src 'self' data:;
      frame-src https://dashboard.twitch.tv;
      connect-src 'self';
    """
